apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitops-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: gitops-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
#  StartingCSV: gitops-operator.v0.0.2
